# Generated by Django 3.1.1 on 2021-01-15 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='order_number',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
