# Generated by Django 3.1.1 on 2021-01-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210106_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='order_number',
            field=models.CharField(default=None, max_length=20, unique=True),
        ),
    ]
