# Generated by Django 3.1.1 on 2021-01-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderrequest_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='order_number',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
