# Generated by Django 3.1.1 on 2021-01-09 06:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderevents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderevents',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 9, 6, 24, 30, 167604, tzinfo=utc)),
        ),
    ]
