# Generated by Django 3.1.1 on 2021-01-09 15:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20210109_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderevents',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 9, 15, 47, 31, 776984, tzinfo=utc)),
        ),
    ]
