# Generated by Django 3.1.1 on 2021-01-09 17:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20210109_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderevents',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 9, 17, 4, 34, 946325, tzinfo=utc)),
        ),
    ]
