# Generated by Django 3.1.1 on 2021-01-10 16:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20210109_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderevents',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 10, 16, 8, 56, 447672, tzinfo=utc)),
        ),
    ]
