# Generated by Django 3.1.1 on 2021-01-13 15:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20210110_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderevents',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 13, 15, 44, 2, 390945, tzinfo=utc)),
        ),
    ]
