# Generated by Django 3.1.1 on 2021-01-13 17:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20210113_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderevents',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 13, 17, 24, 19, 52099, tzinfo=utc)),
        ),
    ]
