# Generated by Django 3.1.1 on 2021-01-15 14:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20210113_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderevents',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 15, 14, 52, 57, 603507, tzinfo=utc)),
        ),
    ]
