# Generated by Django 3.1.1 on 2021-01-13 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_auto_20210113_1544'),
        ('purchase', '0003_auto_20210110_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequisitionproductlist',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pr_product', to='inventory.productmaster'),
        ),
        migrations.AddField(
            model_name='purchaserequisitionproductlist',
            name='product_code',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequisitionproductlist',
            name='product_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequisitionproductlist',
            name='store',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
