# Generated by Django 3.1.1 on 2021-01-13 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_auto_20210113_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequisitionproductlist',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requisition_unit', to='inventory.unitmaster'),
        ),
    ]
