# Generated by Django 3.1.1 on 2021-01-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_auto_20210113_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequisitionproductlist',
            name='expected_date',
            field=models.DateField(null=True),
        ),
    ]
