# Generated by Django 3.1.1 on 2021-01-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_auto_20210113_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequisition',
            name='approved_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='approved_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
