# Generated by Django 3.1.1 on 2021-01-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_auto_20210115_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequisitionproductlist',
            name='required_qty',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
