# Generated by Django 3.1.1 on 2021-01-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_auto_20210116_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequisitionproductlist',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
