# Generated by Django 3.1.1 on 2021-01-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_poorderrequest'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='purchaserequisitionproductlist',
        #     name='active',
        #     field=models.BooleanField(default=True),
        # ),
        migrations.AlterField(
            model_name='purchaserequisitionproductlist',
            name='required_qty',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
