# Generated by Django 3.1.1 on 2021-01-23 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0009_purchaserequisitionproductlist_active'),
        ('purchase', '0008_poorderrequest'),
    ]

    operations = [
    ]
