# Generated by Django 3.1.1 on 2021-01-21 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0010_poorderdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='poorderdetails',
            name='po_order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='purchase.poorderrequest'),
        ),
    ]
