# Generated by Django 3.1.1 on 2021-01-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0012_poorderrequest_pr_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='poorderdetails',
            name='product_code',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='poorderdetails',
            name='product_name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
