# Generated by Django 3.1.1 on 2021-01-27 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0013_grnmaster_grnproductlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grnmaster',
            name='vendor',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
