# Generated by Django 3.1.1 on 2021-01-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0013_auto_20210121_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='poorderrequest',
            name='po_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='poorderrequest',
            name='po_raised_by',
            field=models.CharField(blank=None, max_length=500, null=True),
        ),
    ]
