# Generated by Django 3.1.1 on 2021-01-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0014_auto_20210121_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poorderdetails',
            name='delivery_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='poorderrequest',
            name='po_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
