# Generated by Django 3.1.1 on 2021-01-27 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0014_auto_20210127_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='grnmaster',
            name='invoice_doc',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/upload/grn/invoice_do'),
        ),
    ]
