# Generated by Django 3.1.1 on 2021-01-23 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0015_auto_20210121_1533'),
        ('purchase', '0010_merge_20210123_0533'),
    ]

    operations = [
    ]
