# Generated by Django 3.1.1 on 2021-01-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0016_auto_20210127_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='grnproductlist',
            name='batch_code',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='grnproductlist',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
    ]
