# Generated by Django 3.1.1 on 2021-01-27 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0016_merge_20210123_0627'),
        ('purchase', '0017_auto_20210127_1325'),
    ]

    operations = [
    ]
