# Generated by Django 3.1.1 on 2021-01-27 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_store_is_head_office'),
        ('purchase', '0018_merge_20210127_1614'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='purchaserequisitionproductlist',
        #     name='active',
        #     field=models.BooleanField(default=True),
        # ),
        migrations.AddField(
            model_name='purchaserequisitionproductlist',
            name='store_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_pr', to='store.store'),
        ),
        migrations.AlterField(
            model_name='poorderdetails',
            name='delivery_date',
            field=models.DateField(null=True),
        ),
    ]
