# Generated by Django 3.1.1 on 2021-01-28 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_store_is_head_office'),
        ('purchase', '0019_auto_20210127_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='grnmaster',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grn_store', to='store.store'),
        ),
        migrations.AddField(
            model_name='poorderrequest',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_po_req', to='store.store'),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_pur_req', to='store.store'),
        ),
        # migrations.AddField(
        #     model_name='purchaserequisitionproductlist',
        #     name='active',
        #     field=models.BooleanField(default=True),
        # ),
    ]
