# Generated by Django 3.1.1 on 2021-02-11 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstock',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.store'),
        ),
        migrations.AddField(
            model_name='productstock',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productstock_unit_master', to='inventory.unitmaster'),
        ),
        migrations.AddField(
            model_name='productpricemaster',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_price', to='inventory.productmaster'),
        ),
        migrations.AddField(
            model_name='productpricemaster',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_unit_master', to='inventory.unitmaster'),
        ),
        migrations.AddField(
            model_name='productmaster',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_brand', to='inventory.productbrandmaster'),
        ),
        migrations.AddField(
            model_name='productmaster',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='inventory.productcategory'),
        ),
        migrations.AddField(
            model_name='productmaster',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sub_category', to='inventory.productsubcategory'),
        ),
        migrations.AddField(
            model_name='productimages',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='inventory.productmaster'),
        ),
    ]
