# Generated by Django 3.1.1 on 2020-12-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmaster',
            name='product_attributes',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='productbrandmaster',
            name='brand_image',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='static/upload/product/brands'),
        ),
        migrations.AlterField(
            model_name='productmaster',
            name='product_image',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='static/upload/product/products'),
        ),
    ]
