# Generated by Django 3.1.1 on 2020-12-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20201225_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaster',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/upload/product/products'),
        ),
    ]
