# Generated by Django 3.1.1 on 2020-12-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20201225_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmaster',
            name='product_pack_types',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
