# Generated by Django 3.1.1 on 2020-12-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_productmaster_product_pack_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpricemaster',
            name='batch_expiry',
        ),
        migrations.RemoveField(
            model_name='productpricemaster',
            name='batch_number',
        ),
        migrations.RemoveField(
            model_name='productpricemaster',
            name='ob_qty',
        ),
        migrations.RemoveField(
            model_name='productpricemaster',
            name='primaryunit_price_buy',
        ),
        migrations.RemoveField(
            model_name='productpricemaster',
            name='primaryunit_price_sell',
        ),
        migrations.RemoveField(
            model_name='productpricemaster',
            name='secondaryunit_price_buy',
        ),
        migrations.RemoveField(
            model_name='productpricemaster',
            name='secondaryunit_price_sell',
        ),
        migrations.RemoveField(
            model_name='productpricemaster',
            name='store',
        ),
        migrations.AddField(
            model_name='productpricemaster',
            name='buy_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='productpricemaster',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='productpricemaster',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productpricemaster',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
