# Generated by Django 3.1.1 on 2021-01-06 14:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_storeuser'),
        ('inventory', '0007_auto_20201230_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstock',
            name='batch_expiry',
            field=models.DateField(default=datetime.datetime(2021, 1, 6, 14, 58, 12, 477036), null=True),
        ),
        migrations.AddField(
            model_name='productstock',
            name='batch_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productstock',
            name='grn_number',
            field=models.CharField(blank=True, default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='productstock',
            name='pack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.productpricemaster'),
        ),
        migrations.AddField(
            model_name='productstock',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.store'),
        ),
    ]
