# Generated by Django 3.1.1 on 2021-01-07 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20210107_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstock',
            name='batch_expiry',
            field=models.DateField(default=datetime.datetime(2021, 1, 7, 18, 18, 25, 568889), null=True),
        ),
    ]
