# Generated by Django 3.1.1 on 2021-01-09 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_auto_20210109_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpricemaster',
            name='bar_code',
            field=models.ImageField(blank=True, upload_to='static/upload/product/barcodes'),
        ),
        migrations.AddField(
            model_name='productpricemaster',
            name='product_identifier',
            field=models.IntegerField(default=0, max_length=12),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='batch_expiry',
            field=models.DateField(default=datetime.datetime(2021, 1, 9, 15, 33, 51, 725489), null=True),
        ),
    ]
