# Generated by Django 3.1.1 on 2021-01-09 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_auto_20210109_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpricemaster',
            name='bar_code',
            field=models.ImageField(default='', upload_to='static/upload/product/barcodes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productstock',
            name='batch_expiry',
            field=models.DateField(default=datetime.datetime(2021, 1, 9, 15, 47, 31, 771307), null=True),
        ),
    ]
