# Generated by Django 3.1.1 on 2021-01-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_auto_20210110_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstock',
            name='batch_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
