# Generated by Django 3.1.1 on 2021-01-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_auto_20210110_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpricemaster',
            name='product_identifier',
            field=models.CharField(default=0, max_length=12),
        ),
    ]
