# Generated by Django 3.1.1 on 2021-01-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_auto_20210110_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsubcategory',
            name='description',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
