# Generated by Django 3.1.1 on 2021-01-09 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_auto_20210109_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstock',
            name='batch_expiry',
            field=models.DateField(default=datetime.datetime(2021, 1, 9, 17, 23, 6, 494470), null=True),
        ),
    ]
