# Generated by Django 3.1.1 on 2021-01-27 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_productsubcategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstock',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productstock_unit_master', to='inventory.unitmaster'),
        ),
    ]
