# Generated by Django 3.1.1 on 2021-01-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_productstock_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstock',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
