# Generated by Django 3.1.1 on 2021-01-13 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_auto_20210113_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstock',
            name='batch_expiry',
            field=models.DateField(default=datetime.datetime(2021, 1, 13, 16, 56, 51, 458027), null=True),
        ),
    ]
