# Generated by Django 3.1.1 on 2021-01-17 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_auto_20210116_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstock',
            name='batch_expiry',
            field=models.DateField(default=datetime.datetime(2021, 1, 17, 13, 25, 20, 343390), null=True),
        ),
    ]
