# Generated by Django 3.1.1 on 2021-01-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_cart_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
