# Generated by Django 3.1.1 on 2021-01-26 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_storeshiplocations'),
        ('sales', '0003_auto_20210110_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.store'),
        ),
    ]
