# Generated by Django 3.1.1 on 2021-01-16 14:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20210115_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderevents',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 16, 14, 18, 45, 574500, tzinfo=utc)),
        ),
    ]
