# Generated by Django 3.1.1 on 2021-01-17 13:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20210116_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderevents',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 17, 13, 25, 20, 349958, tzinfo=utc)),
        ),
    ]
