# Generated by Django 3.1.1 on 2021-01-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_storeshiplocations'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_head_office',
            field=models.BooleanField(default=False),
        ),
    ]
